### ISSUE TITLE
keys issue 

### ISSUE THREAD

**Issue by G4m3it** [RSATom/VKVideoStreamer#1]
we in africa can't get the video keys as we cant sign up on Vk, our accounts gets blocked, secondly snap run vk-video-stream pops an error

error: snap cannot find app "vk-video-streamer" in "vk-video-streamer"

**Comment by RSATom** [comment]
I'm not sure how I could help you with blocked VK account...

**Comment by RSATom** [comment]
> error: snap cannot find app "vk-video-streamer" in "vk-video-streamer"

Where did you see this error? Did you use `snap logs` command?

**Comment by RSATom** [comment]
I think I understood what you are trying to do: you are trying to start app with `snap run` - it's wrong. App is running as background daemon, so all you need to do is edit config and restart snap with `snap restart`.
